version: "3.8"
services:
  movie_service:
    image: xsis:v1.0.0
    stdin_open: true
    tty: true
    container_name: xsis_movie_api
    restart: always
    environment:
            TZ: "Asia/Jakarta"
    ports:
        - 8888:8888    
    networks:
      vpcbr:
        ipv4_address: '192.168.1.3'   
    volumes:
        - ./config:/app/config
        - /etc/hosts:/etc/hosts
        
  mysql:
    image: mysql:5.7
    stdin_open: true
    tty: true
    container_name: database_mysql
    restart: always
    environment:
        MYSQL_DATABASE: 'xsis'
        MYSQL_USER: 'muhammad'
        MYSQL_PASSWORD: '18121990'
        MYSQL_ROOT_PASSWORD: '18121990'
    ports:
        - '9907:3306'
    expose:
        - '3306'
    networks:
        vpcbr:
            ipv4_address: '192.168.1.2'
    volumes:
        - ./mydb:/var/lib/mysql:rw,delegated
        # - ./config/mysql.cnf:/etc/mysql/conf.d/mysql.cnf:ro

networks:
    vpcbr:
        driver: bridge
        ipam:
            config:
                - subnet: 192.168.1.1/24